tasks:
  - name: Start MySQL and Install Node.js Dependencies
    init: |
      docker-compose up -d
      npm install --prefix upload_this

ports:
  - port: 3000
    onOpen: open-preview
  - port: 3306
    onOpen: ignore