version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wacrm_db
      MYSQL_USER: wacrm_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/import.sql:/docker-entrypoint-initdb.d/import.sql

volumes:
  db_data:
